require('settings')
require('keymaps')
require('plugins')

require('modules.statusline')
require('modules.indent')
require('modules.telescope')
require('modules.nvimtree')
require('modules.autopairs')
require('modules.hop')
require('modules.completion')
require('modules.lspconfig')
require('modules.gitsigns')
require('modules.go')
require('modules.comment')
