require('settings')
require('keymaps')
require('plugins')

require('modules.statusline')
require('modules.telescope')
require('modules.treesitter')
require('modules.nvimtree')
require('modules.autopairs')
require('modules.hop')
require('modules.indent')
require('modules.completion')
require('modules.lspconfig')
require('modules.lsp_signature')
require('modules.truezen')
require('modules.gitsigns')
